package presentacio;


import domini.controladors.CtrlSessio;
import domini.controladors.CtrlWikipedia;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayList;

/**
 * Grup 3: Wikipedia
 * Usuari: ricard.gascons
 * Data: 5/22/15
 */
public class IniciWikipedia extends javax.swing.JFrame {

    /**
     * Creates new form IniciWikipedia
     */
    public IniciWikipedia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        textExaminar = new javax.swing.JTextField();
        examinar = new javax.swing.JButton();
        importarICrearSessio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        crearNovaSessio = new javax.swing.JButton();
        carregarSessio = new javax.swing.JButton();
        llistatSessions = new javax.swing.JComboBox();
        textNomSessioNova = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel2.setVisible(false);
        setTitle("Wikipedia");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 480));
        setResizable(false);

        textExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listenerTextExaminar(evt);
            }
        });

        examinar.setText("Examinar...");
        examinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listenerExaminar(evt);
            }
        });

        importarICrearSessio.setText("Importar i crear");
        importarICrearSessio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listenerImportarICrearSessio(evt);
            }
        });

        jLabel1.setText("Importar fitxer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(textExaminar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(examinar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(importarICrearSessio, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textExaminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(examinar))
                                .addGap(18, 18, 18)
                                .addComponent(importarICrearSessio)
                                .addContainerGap(42, Short.MAX_VALUE))
        );

        crearNovaSessio.setLabel("Crear Sessió");
        crearNovaSessio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listenerCrearNovaSessio(evt);
            }
        });

        carregarSessio.setText("Carregar Sessió");
        carregarSessio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                listenerCarregarSessio(evt);
            }
        });

        actualitzarNomsSessio();

        llistatSessions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listenerLlistatSessions(evt);
            }
        });

        textNomSessioNova.setToolTipText("Nom sessió..");

        jLabel2.setText("Nova sessió creada!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textNomSessioNova, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(crearNovaSessio, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(llistatSessions, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carregarSessio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(38, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(crearNovaSessio)
                                        .addComponent(carregarSessio)
                                        .addComponent(llistatSessions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textNomSessioNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addContainerGap(16, Short.MAX_VALUE))
        );

        textNomSessioNova.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }

    private void listenerExaminar(java.awt.event.ActionEvent evt) {
        int returnVal = jFileChooser1.showOpenDialog(IniciWikipedia.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            Path path = jFileChooser1.getSelectedFile().toPath();
            nomSessioImportada = jFileChooser1.getSelectedFile().getName();
            textExaminar.setText(path.toString());
            //This is where a real application would open the file.

        }
    }

    private void listenerImportarICrearSessio(java.awt.event.ActionEvent evt) {
        String pathSessioImportada = textExaminar.getText();
        try {
            CtrlSessio.getInstance().crearNovaSessio(nomSessioImportada);
            CtrlWikipedia.getInstance().getGrafWikiFromFile(pathSessioImportada);
            MainWindow mainWindow = new MainWindow();
            mainWindow.setVisible(true);
            setVisible(false);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void listenerTextExaminar(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void listenerCrearNovaSessio(java.awt.event.ActionEvent evt) {
        if (!textNomSessioNova.getText().isEmpty()) {
            String nomSessio = textNomSessioNova.getText();
            try {
                if (CtrlSessio.getInstance().crearNovaSessio(nomSessio)) {
                    actualitzarNomsSessio();
                    jLabel2.setVisible(true);
                } else {
                    jLabel2.setVisible(false);
                    JOptionPane.showMessageDialog(this, "Aquest usuari ja existeix!");
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    private void listenerLlistatSessions(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void listenerCarregarSessio(java.awt.event.ActionEvent evt) {
        String nomSessioSeleccionat = llistatSessions.getSelectedItem().toString();
       CtrlSessio.setSessioJaCreada(nomSessioSeleccionat);
        MainWindow mainWindow = new MainWindow();
        setVisible(false);
        mainWindow.setVisible(true);
    }

    private void actualitzarNomsSessio() {
        nomsSessio = new ArrayList<>();
        nomsSessio.add("Error al carregar dades");
        try {
            nomsSessio = CtrlSessio.getNomsSessions();
            if (nomsSessio.isEmpty()) nomsSessio.add("No hi ha sessions");
        } catch (IOException e) {
            e.printStackTrace();
        }
        llistatSessions.setModel(new javax.swing.DefaultComboBoxModel(nomsSessio.toArray()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciWikipedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciWikipedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciWikipedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciWikipedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciWikipedia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton examinar;
    private javax.swing.JButton importarICrearSessio;
    private javax.swing.JButton crearNovaSessio;
    private javax.swing.JButton carregarSessio;
    private javax.swing.JComboBox llistatSessions;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField textExaminar;
    private javax.swing.JTextField textNomSessioNova;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration

    private ArrayList<String> nomsSessio;
    private String nomSessioImportada;

    private class HintTextField extends JTextField implements FocusListener {

        private final String hint;
        private boolean showingHint;

        public HintTextField(final String hint) {
            super(hint);
            this.hint = hint;
            this.showingHint = true;
            super.addFocusListener(this);
        }

        @Override
        public void focusGained(FocusEvent e) {
            if(this.getText().isEmpty()) {
                super.setText("");
                showingHint = false;
            }
        }
        @Override
        public void focusLost(FocusEvent e) {
            if(this.getText().isEmpty()) {
                super.setText(hint);
                showingHint = true;
            }
        }

        @Override
        public String getText() {
            return showingHint ? "" : super.getText();
        }
    }
}
